export const base_url = `http://65.108.61.88:8087/etl`;

export const EVENTS = {
    UPDATE_STORAGE: "UPDATE_STORAGE",
    CLOSE_DROPDOWN: "CLOSE_DROPDOWN",
};

export const SORT_ORDERS = {
    ASC: "ASC",
    DESC: "DESC",
};

export const TABLES = {
    DATASOURCE_LIST: "DATASOURCE_LIST",
    DATASOURCE_TABLE_STRUCTURE: "DATASOURCE_TABLE_STRUCTURE",
    DATASOURCE_TABLE_PREVIEW: "DATASOURCE_TABLE_PREVIEW",
    PROCESSES_LIST: "PROCESSES_LIST",
};

export const MODALS = {
    CREATE_DATA_SOURCE_MODAL: "CREATE_DATA_SOURCE_MODAL",
    EDIT_DATA_SOURCE_MODAL: "EDIT_DATA_SOURCE_MODAL",
    DATASOURCE_AD_HOC_QUERY_MODAL: "DATASOURCE_AD_HOC_QUERY_MODAL",
    CREATE_PROCESS_MODAL: "CREATE_PROCESS_MODAL",
    EDIT_PROCESS_ATTRIBUTES: "EDIT_PROCESS_ATTRIBUTES",
};

export const FORMS = {
    CREATE_DATA_SOURCE_MODAL: "CREATE_DATA_SOURCE_FORM",
    EDIT_DATA_SOURCE_MODAL: "EDIT_DATA_SOURCE_FORM",
    DATASOURCE_AD_HOC_FORM: "DATASOURCE_AD_HOC_FORM",
    CREATE_PROCESS_MODAL: "CREATE_PROCESS_MODAL",
    EDIT_PROCESS_ATTRIBUTES: "EDIT_PROCESS_ATTRIBUTES",
};
