export const API_URL = `https://gnx.dev.softlab360.com`;

export const EVENTS = {
    UPDATE_STORAGE: "UPDATE_STORAGE",
    CLOSE_DROPDOWN: "CLOSE_DROPDOWN",
};

export const SORT_ORDERS = {
    ASC: "ASC",
    DESC: "DESC",
};

export const TABLES = {
    DATA_SOURSE_LIST: "DATA_SOURSE_LIST",
};

export const MODALS = {
    CREATE_DATA_SOURCE_MODAL: "CREATE_DATA_SOURCE_MODAL",
    EDIT_DATA_SOURCE_MODAL: "EDIT_DATA_SOURCE_MODAL",
};

export const FORMS = {
    CREATE_DATA_SOURCE_MODAL: "CREATE_DATA_SOURCE_MODAL",
    EDIT_DATA_SOURCE_MODAL: "EDIT_DATA_SOURCE_MODAL",
};
