export const base_url = `http://65.108.61.88:8087/etl`;

export const EVENTS = {
    UPDATE_STORAGE: "UPDATE_STORAGE",
    CLOSE_DROPDOWN: "CLOSE_DROPDOWN",
};

export const SORT_ORDERS = {
    ASC: "ASC",
    DESC: "DESC",
};

export const TABLES = {
    DATASOURCE_LIST: "DATASOURCE_LIST",
    DATASOURCE_TABLE_STRUCTURE: "DATASOURCE_TABLE_STRUCTURE",
    DATASOURCE_TABLE_PREVIEW: "DATASOURCE_TABLE_PREVIEW",
};

export const MODALS = {
    CREATE_DATA_SOURCE_MODAL: "CREATE_DATA_SOURCE_MODAL",
    EDIT_DATA_SOURCE_MODAL: "EDIT_DATA_SOURCE_MODAL",
};

export const FORMS = {
    CREATE_DATA_SOURCE_MODAL: "CREATE_DATA_SOURCE_MODAL",
    EDIT_DATA_SOURCE_MODAL: "EDIT_DATA_SOURCE_MODAL",
};
