name: Frontend deploy
on:
    push:
        branches:
            # - "main"
            - "GitHub-actions-setup"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm build
            - name: Surge deployment
              run: surge --project ./build/ --domain etl.surge.sh
            # Login to Docker Hub
            # - name: Login to Docker Hub
            #   uses: docker/login-action@v1
            #   with:
            #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
            #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            # # Set up Docker build environment
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v1
            # # Build Dockerfile and push IMAGE to Docker Hub
            # - name: Build and push
            #   uses: docker/build-push-action@v2
            #   with:
            #       context: .
            #       file: ./Dockerfile
            #       push: true
            #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
            # # Create SSH connection
            # - name: Install SSH Key
            #   uses: shimataro/ssh-key-action@v2.3.1
            #   with:
            #       key: ${{ secrets.SSH_PRIVATE_KEY }}
            #       known_hosts: ${{ secrets.SERVER_KNOWN_HOSTS }}
            # - name: Adding Known Hosts
            #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            # # Delete old files from server
            # - name: Delete old files from server
            #   run: |
            #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            #         rm -rf ${{ secrets.DOCKER_HUB_REPO }}
            #         mkdir ${{ secrets.DOCKER_HUB_REPO }}
            #       "
            # # Copy files to server
            # - name: Copy files to server
            #   run: scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:./${{ secrets.DOCKER_HUB_REPO }}/;
            # # Copy restart script to server
            # - name: Copy restart script to server
            #   run: scp restart.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:./${{ secrets.DOCKER_HUB_REPO }}/;
            # # Run restart script
            # - name: Run restart script
            #   run: |
            #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            #         cd ${{ secrets.DOCKER_HUB_REPO }}
            #         chmod +x restart.sh
            #         ./restart.sh
            #       "